search-biases:
  # Brief regex review:
  #   `^` indicates the beginning of the string
  #   `$` indicates the end of the string
  #   `\b` indicates a word boundary
  #   `(?i)` means case insensitive

  - regex: ^(?i)browser$
    convert-to: web browser
    boost-appids:
      - app.zen_browser.zen
      - io.github.ungoogled_software.ungoogled_chromium
      - org.chromium.Chromium
      - org.gnome.Epiphany
      - org.kde.falkon
      - org.mozilla.firefox
      - org.torproject.torbrowser-launcher

  - regex: \b(?i)vm\b
    convert-to: virtual machine
    boost-appids:
      - org.virt_manager.virt-manager
      - org.gnome.Boxes

  - regex: \b(?i)ide\b
    convert-to: develop
    boost-appids:
      - com.visualstudio.code
      - com.vscodium.codium
      - dev.zed.Zed
      - org.gnome.Builder
      - org.kde.kdevelop

  - regex: \b(?i)yt\b
    convert-to: youtube
